"""
Wikidata RAG Integration
Retrieval-Augmented Generation for XAI snippets.
Fetches factual descriptions and statements from Wikidata
to ground AI explanations in real, verifiable information.

API: https://www.wikidata.org/w/rest.php/wikibase/v1
No key required — open Linked Data.
"""
import httpx
from typing import Optional

WIKIDATA_REST = "https://www.wikidata.org/w/rest.php/wikibase/v1"

# In-process cache: {qid -> description_str}  — Wikidata descriptions don't change often
_wiki_cache: dict[str, str] = {}

# Pre-mapped Wikidata QIDs for our destination set (saves a search roundtrip)
DEST_WIKIDATA_QIDS = {
    "1":  "Q5765",    # Bali
    "2":  "Q39760",   # Patagonia
    "3":  "Q14524",   # Santorini
    "4":  "Q34600",   # Kyoto
    "5":  "Q36774",   # Machu Picchu
    "6":  "Q11843",   # Reykjavik
    "7":  "Q843472",  # Masai Mara
    "8":  "Q192550",  # Amalfi Coast
    "9":  "Q22690",   # Queenstown
    "10": "Q101173",  # Marrakech
    "11": "Q826",     # Maldives
    "12": "Q1085",    # Prague
    "13": "Q207492",  # Banff NP
    "15": "Q1490",    # Tokyo
    "16": "Q42312",   # Petra
    "21": "Q11927",   # Swiss Alps
    "22": "Q43473",   # Angkor Wat
    "23": "Q1492",    # Barcelona
    "24": "Q8678",    # Rio de Janeiro
    "35": "Q19825",   # Norwegian Fjords
    "39": "Q917",     # Bhutan
    "40": "Q15292",   # Tuscany
    "44": "Q16897",   # Palawan
    "47": "Q40482",   # Oaxaca
    "48": "Q76566",   # Ha Long Bay
    "49": "Q179985",  # Serengeti
    "57": "Q1140",    # Kathmandu
    "59": "Q608917",  # Tulum
    "62": "Q201124",  # Cappadocia
    "66": "Q37070",   # Great Barrier Reef
    "72": "Q194404",  # Wadi Rum
    "74": "Q193375",  # Inca Trail
    "75": "Q214696",  # Socotra
    "80": "Q351",     # Yellowstone
    "84": "Q6465",    # Dolomites
    "86": "Q14452",   # Easter Island
    "91": "Q5084",    # Zhangjiajie
    "95": "Q351981",  # Yosemite Valley
}


async def fetch_wikidata_description(qid: str) -> Optional[str]:
    """Fetch the English description of a Wikidata entity by QID (cached)."""
    if qid in _wiki_cache:
        return _wiki_cache[qid]
    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(
                f"{WIKIDATA_REST}/entities/items/{qid}",
                headers={"Accept": "application/json"},
            )
            if resp.status_code != 200:
                return None

            data = resp.json()
            desc = (
                data.get("descriptions", {})
                    .get("en", {})
                    .get("value", "")
            )
            if desc:
                _wiki_cache[qid] = desc
                return desc
            return None

    except Exception:
        return None


async def fetch_wikidata_statements(qid: str, props: list[str]) -> dict:
    """
    Fetch specific property statements for a Wikidata entity.
    props: list of property IDs like ['P18', 'P625', 'P856']
    Returns { prop_id: value_string }
    """
    result = {}
    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            resp = await client.get(
                f"{WIKIDATA_REST}/entities/items/{qid}/statements",
                headers={"Accept": "application/json"},
            )
            if resp.status_code != 200:
                return result

            statements = resp.json()
            for prop in props:
                prop_statements = statements.get(prop, [])
                if prop_statements:
                    # Get the first preferred or normal rank statement value
                    for stmt in prop_statements:
                        val = stmt.get("value", {})
                        if isinstance(val, dict):
                            content = val.get("content")
                            if content:
                                result[prop] = str(content)
                                break
                        elif isinstance(val, str):
                            result[prop] = val
                            break
    except Exception:
        pass
    return result


async def rag_enrich_xai(dest_id: str, dest_name: str, base_xai: str) -> str:
    """
    Retrieval-Augmented Generation for XAI snippets.
    Fetches a Wikidata description and appends a factual sentence
    to the base XAI explanation generated by the hybrid engine.
    """
    qid = DEST_WIKIDATA_QIDS.get(str(dest_id))
    if not qid:
        return base_xai  # No QID mapped — return base explanation unchanged

    description = await fetch_wikidata_description(qid)
    if not description:
        return base_xai

    # Trim description to a digestible length
    if len(description) > 120:
        description = description[:120].rstrip() + "…"

    # Compose enriched XAI: base engine output + Wikidata factual grounding
    enriched = f"{base_xai} Wikidata: {description}."
    return enriched


async def search_wikidata_entity(query: str) -> Optional[str]:
    """
    Search Wikidata for a destination name and return the top QID.
    Used for destinations not in the pre-mapped dict.
    """
    try:
        async with httpx.AsyncClient(timeout=6.0) as client:
            resp = await client.get(
                "https://www.wikidata.org/w/api.php",
                params={
                    "action": "wbsearchentities",
                    "search": query,
                    "language": "en",
                    "format": "json",
                    "limit": 1,
                    "type": "item",
                },
            )
            if resp.status_code == 200:
                results = resp.json().get("search", [])
                if results:
                    return results[0].get("id")
    except Exception:
        pass
    return None
